# Generated by Django 4.1.1 on 2022-11-21 05:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='air-company/', verbose_name='image of air companies')),
                ('name', models.CharField(max_length=50, verbose_name='name of air companies')),
            ],
            options={
                'verbose_name': 'air company',
                'verbose_name_plural': 'air companies',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CheapFlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cheap-flight/', verbose_name='images')),
                ('where_to', models.CharField(max_length=50, verbose_name='where to')),
                ('date', models.DateField()),
                ('direct_flight', models.CharField(max_length=50, verbose_name='direct flight')),
                ('company_logo', models.ImageField(upload_to='company-logo/', verbose_name='company logo')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'cheap flight',
                'verbose_name_plural': 'cheap flights',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='city name')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DiscoverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='discover/', verbose_name='image')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'discover',
                'verbose_name_plural': 'discovers',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='RecommendationDestinationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/', verbose_name='images')),
                ('where_to', models.CharField(max_length=50, verbose_name='where to')),
                ('date', models.DateField()),
                ('direct_flight', models.CharField(max_length=50, verbose_name='direct flight')),
                ('company_logo', models.ImageField(upload_to='company-logo/', verbose_name='company logo')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'destination',
                'verbose_name_plural': 'destinations',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TerminalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='name of terminal')),
            ],
            options={
                'verbose_name': 'terminal',
                'verbose_name_plural': 'terminals',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('series', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='series')),
                ('gate', models.CharField(max_length=3, verbose_name='gate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='company', to='main.aircompanymodel')),
                ('flight_from', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flight_from', to='main.citymodel', verbose_name='from')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='terminal', to='main.terminalmodel')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to', to='main.citymodel', verbose_name='to')),
            ],
            options={
                'verbose_name': 'flight',
                'verbose_name_plural': 'flights',
            },
        ),
    ]
