# Generated by Django 4.1.1 on 2022-10-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationDestinationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/', verbose_name='images')),
                ('where_to', models.CharField(max_length=50, verbose_name='where to')),
                ('date', models.DateField(auto_now=True)),
                ('direct_flight', models.CharField(max_length=50, verbose_name='direct flight')),
                ('company_logo', models.ImageField(upload_to='company-logo/', verbose_name='company logo')),
                ('price', models.PositiveIntegerField(max_length=4, verbose_name='price')),
            ],
            options={
                'verbose_name': 'destination',
                'verbose_name_plural': 'destinations',
                'ordering': ('-id',),
            },
        ),
    ]
