# Generated by Django 4.1.1 on 2022-10-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationdestinationsmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
