# Generated by Django 4.1.1 on 2022-11-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightmodel',
            name='live_status',
            field=models.PositiveIntegerField(choices=[(1, 'On air'), (2, 'In block')], default=2, verbose_name='live status'),
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'On time'), (2, 'Delayed')], default=1, verbose_name='status'),
        ),
    ]
