# Generated by Django 4.1.1 on 2022-11-21 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_flightmodel_live_status_flightmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='series',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='series'),
        ),
    ]
