# Generated by Django 4.1.1 on 2022-10-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_recommendationdestinationsmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='discover/', verbose_name='image')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'discover',
                'verbose_name_plural': 'discovers',
                'ordering': ('-id',),
            },
        ),
    ]
