# Generated by Django 4.1.1 on 2022-11-24 11:17

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_flightmodel_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='date',
            field=models.DateField(validators=[config.validators.today_validate], verbose_name='date'),
        ),
    ]
