# Generated by Django 4.1.1 on 2022-11-16 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_messagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='air-company/', verbose_name='image of air companies')),
                ('name', models.CharField(max_length=50, verbose_name='name of air companies')),
            ],
            options={
                'verbose_name': 'air company',
                'verbose_name_plural': 'air companies',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email'),
        ),
    ]
