# Generated by Django 4.1.1 on 2022-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aircompanymodel_alter_messagemodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='name of terminal')),
            ],
            options={
                'verbose_name': 'terminal',
                'verbose_name_plural': 'terminals',
                'ordering': ('-id',),
            },
        ),
    ]
