# Generated by Django 4.1.1 on 2022-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_terminalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPlaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=60, verbose_name='destination')),
            ],
            options={
                'verbose_name': 'destination',
                'verbose_name_plural': 'destinations',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='cheapflightmodel',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='recommendationdestinationsmodel',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
    ]
