# Generated by Django 4.1.1 on 2022-11-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_flightplacemodel_alter_cheapflightmodel_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightplacemodel',
            options={'ordering': ('-id',), 'verbose_name': 'flight destination', 'verbose_name_plural': 'flight destinations'},
        ),
    ]
