# Generated by Django 4.1.1 on 2022-11-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_alter_flightmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='seat class name')),
                ('number', models.CharField(max_length=2, verbose_name='seat number')),
            ],
            options={
                'verbose_name': 'seat',
                'verbose_name_plural': 'seats',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(max_length=6, verbose_name='ticket price')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flight', to='main.flightmodel', verbose_name='flights')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seat', to='tickets.seatmodel', verbose_name='ticket seat')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ('-id',),
            },
        ),
    ]
