# Generated by Django 4.1.1 on 2022-11-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_seatmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmodel',
            name='name',
            field=models.PositiveIntegerField(choices=[('E', 'Ekonom'), ('B', 'Biznes'), ('P', 'Premum')], verbose_name='seat class name'),
        ),
    ]
